name: 'Setup Qualification Environment'
description: 'Checks out the repository and sets up the qualification environment (R, PK-Sim, QualificationRunner) with caching support'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Configure git and Set R library path
      run: |
        git config --global core.longpaths true
        echo "R_LIBS_USER=${{ github.workspace }}/RLibrary" >> $GITHUB_ENV
      shell: bash

    # Restore previously prepared environment if tools.csv was unchanged
    - name: Restore setup cache
      id: cache-setup
      uses: actions/cache/restore@v5
      with:
        key: ospsuite-${{ hashFiles('tools.csv') }}
        path: |
          ${{ github.workspace }}/RLibrary
          ${{ github.workspace }}/PK-Sim
          ${{ github.workspace }}/QualificationRunner

    # Always compute the R version from tools.csv so we can install R on cached runs
    - id: get-tools-versions
      name: Get tools versions (for R setup on cached runs)
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/get-tools-versions@main
      with:
        tools-path: tools.csv

    # If we restored the environment, we still need to make R, Pandoc, and chromehtml2pdf available
    - name: Setup R (cached run)
      if: steps.cache-setup.outputs.cache-hit == 'true'
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '${{ steps.get-tools-versions.outputs.r }}'
        use-public-rspm: true

    - name: Setup Pandoc (cached run)
      if: steps.cache-setup.outputs.cache-hit == 'true'
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install chromehtml2pdf (cached run)
      if: steps.cache-setup.outputs.cache-hit == 'true'
      run: npm install -g chromehtml2pdf
      shell: bash

    - id: qualification-environment
      if: steps.cache-setup.outputs.cache-hit != 'true'
      name: Setup Qualification Environment
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/setup-qualification-environment@main
      with:
        tools-path: tools.csv

    - name: Downgrade ggplot2 to 3.5.2
      if: steps.cache-setup.outputs.cache-hit != 'true'
      run: |
        Rscript -e 'remove.packages("ggplot2")'
        Rscript -e 'remotes::install_version("ggplot2", version = "3.5.2", repos = "https://cran.r-project.org")'
      shell: bash

    # Save the prepared environment so subsequent runs can skip setup
    - name: Save setup cache
      if: steps.cache-setup.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: ospsuite-${{ hashFiles('tools.csv') }}
        path: |
          ${{ github.workspace }}/RLibrary
          ${{ github.workspace }}/PK-Sim
          ${{ github.workspace }}/QualificationRunner
